.data
.code
_cpy8 PROC
	MOV R8B, BYTE PTR[RCX]
	MOV BYTE PTR[RDX], R8B
	RET
_cpy8 ENDP

_cpy16 PROC
	MOV R8W, WORD PTR[RDX]
	MOV BYTE PTR[RCX+1], R8B
	SHR R8W, 8
	MOV BYTE PTR[RCX+0], R8B
	RET
_cpy16 ENDP
;dest is RCX
;src  is RDX
_cpy32 PROC
	MOV R8D, DWORD PTR[RDX]
	MOV BYTE PTR[RCX+3], R8B
	SHR R8D, 8
	MOV BYTE PTR[RCX+2], R8B
	SHR R8D, 8
	MOV BYTE PTR[RCX+1], R8B
	SHR R8D, 8
	MOV BYTE PTR[RCX+0], R8B
	RET
_cpy32 ENDP

_cpy64 PROC
	
	RET
_cpy64 ENDP

_cpyFloat PROC
	MOV R8D, DWORD PTR[RDX]
	MOV BYTE PTR[RCX+3], R8B
	SHR R8D, 8
	MOV BYTE PTR[RCX+2], R8B
	SHR R8D, 8
	MOV BYTE PTR[RCX+1], R8B
	SHR R8D, 8
	MOV BYTE PTR[RCX+0], R8B
	RET
_cpyFloat ENDP
END