#pragma once

#define 	_GX_TF_CTF   0x20 
#define 	_GX_TF_ZTF   0x10 
#define 	GX_AF_NONE   2 
#define 	GX_AF_SPEC   0 
#define 	GX_AF_SPOT   1 
#define 	GX_ALPHA0   2 
#define 	GX_ALPHA1   3 
#define 	GX_ALPHA_BUMP   7 
#define 	GX_ALPHA_BUMPN   8 
#define 	GX_ALWAYS   7 
#define 	GX_ANISO_1   0 
#define 	GX_ANISO_2   1 
#define 	GX_ANISO_4   2 
#define 	GX_AOP_AND   0 
#define 	GX_AOP_OR   1 
#define 	GX_AOP_XNOR   3 
#define 	GX_AOP_XOR   2 
#define 	GX_BIGTLUT0   16 
#define 	GX_BIGTLUT1   17 
#define 	GX_BIGTLUT2   18 
#define 	GX_BIGTLUT3   19 
#define 	GX_BL_DSTALPHA   6 
#define 	GX_BL_DSTCLR   GX_BL_SRCCLR 
#define 	GX_BL_INVDSTALPHA   7 
#define 	GX_BL_INVDSTCLR   GX_BL_INVSRCCLR 
#define 	GX_BL_INVSRCALPHA   5 
#define 	GX_BL_INVSRCCLR   3 
#define 	GX_BL_ONE   1 
#define 	GX_BL_SRCALPHA   4 
#define 	GX_BL_SRCCLR   2 
#define 	GX_BL_ZERO   0 
#define 	GX_BLEND   2 
#define 	GX_BM_BLEND   1 
#define 	GX_BM_LOGIC   2 
#define 	GX_BM_NONE   0 
#define 	GX_BM_SUBTRACT   3 
#define 	GX_CA_A0   1 
#define 	GX_CA_A1   2 
#define 	GX_CA_A2   3 
#define 	GX_CA_APREV   0 
#define 	GX_CA_KONST   6 
#define 	GX_CA_RASA   5 
#define 	GX_CA_TEXA   4 
#define 	GX_CA_ZERO   7 
#define 	GX_CC_A0   3 
#define 	GX_CC_A1   5 
#define 	GX_CC_A2   7 
#define 	GX_CC_APREV   1 
#define 	GX_CC_C0   2 
#define 	GX_CC_C1   4 
#define 	GX_CC_C2   6 
#define 	GX_CC_CPREV   0 
#define 	GX_CC_HALF   13 
#define 	GX_CC_KONST   14 
#define 	GX_CC_ONE   12 
#define 	GX_CC_RASA   11 
#define 	GX_CC_RASC   10 
#define 	GX_CC_TEXA   9 
#define 	GX_CC_TEXC   8 
#define 	GX_CC_ZERO   15 
#define 	GX_CH_ALPHA   3 
#define 	GX_CH_BLUE   2 
#define 	GX_CH_GREEN   1 
#define 	GX_CH_RED   0 
#define 	GX_CLAMP   0 
#define 	GX_CLAMP_BOTTOM   2 
#define 	GX_CLAMP_NONE   0 
#define 	GX_CLAMP_TOP   1 
#define 	GX_CLIP_DISABLE   1 
#define 	GX_CLIP_ENABLE   0 
#define 	GX_CLR_RGB   0 
#define 	GX_CLR_RGBA   1 
#define 	GX_COLOR0   0 
#define 	GX_COLOR0A0   4 
#define 	GX_COLOR1   1 
#define 	GX_COLOR1A1   5 
#define 	GX_COLORNULL   0xff 
#define 	GX_COLORZERO   6 
#define 	GX_COPY_INTLC_EVEN   2 
#define 	GX_COPY_INTLC_ODD   3 
#define 	GX_COPY_PROGRESSIVE   0 
#define 	GX_CS_DIVIDE_2   3 
#define 	GX_CS_SCALE_1   0 
#define 	GX_CS_SCALE_2   1 
#define 	GX_CS_SCALE_4   2 
#define 	GX_CTF_A8   (0x7|_GX_TF_CTF) 
#define 	GX_CTF_B8   (0xA|_GX_TF_CTF) 
#define 	GX_CTF_G8   (0x9|_GX_TF_CTF) 
#define 	GX_CTF_GB8   (0xC|_GX_TF_CTF) 
#define 	GX_CTF_R4   (0x0|_GX_TF_CTF) 
#define 	GX_CTF_R8   (0x8|_GX_TF_CTF) 
#define 	GX_CTF_RA4   (0x2|_GX_TF_CTF) 
#define 	GX_CTF_RA8   (0x3|_GX_TF_CTF) 
#define 	GX_CTF_RG8   (0xB|_GX_TF_CTF) 
#define 	GX_CTF_YUVA8   (0x6|_GX_TF_CTF) 
#define 	GX_CTF_Z16L   (0xC|_GX_TF_ZTF|_GX_TF_CTF) 
#define 	GX_CTF_Z4   (0x0|_GX_TF_ZTF|_GX_TF_CTF) 
#define 	GX_CTF_Z8L   (0xA|_GX_TF_ZTF|_GX_TF_CTF) 
#define 	GX_CTF_Z8M   (0x9|_GX_TF_ZTF|_GX_TF_CTF) 
#define 	GX_CULL_ALL   3 
#define 	GX_CULL_BACK   2 
#define 	GX_CULL_FRONT   1 
#define 	GX_CULL_NONE   0 
#define 	GX_DA_GENTLE   1 
#define 	GX_DA_MEDIUM   2 
#define 	GX_DA_OFF   0 
#define 	GX_DA_STEEP   3 
#define 	GX_DECAL   1 
#define 	GX_DF_CLAMP   2 
#define 	GX_DF_NONE   0 
#define 	GX_DF_SIGNED   1 
#define 	GX_DIRECT   1 
#define 	GX_DISABLE   0 
#define 	GX_DTTIDENTITY   125 
#define 	GX_DTTMTX0   64 
#define 	GX_DTTMTX1   67 
#define 	GX_DTTMTX10   94 
#define 	GX_DTTMTX11   97 
#define 	GX_DTTMTX12   100 
#define 	GX_DTTMTX13   103 
#define 	GX_DTTMTX14   106 
#define 	GX_DTTMTX15   109 
#define 	GX_DTTMTX16   112 
#define 	GX_DTTMTX17   115 
#define 	GX_DTTMTX18   118 
#define 	GX_DTTMTX19   121 
#define 	GX_DTTMTX2   70 
#define 	GX_DTTMTX3   73 
#define 	GX_DTTMTX4   76 
#define 	GX_DTTMTX5   79 
#define 	GX_DTTMTX6   82 
#define 	GX_DTTMTX7   85 
#define 	GX_DTTMTX8   88 
#define 	GX_DTTMTX9   91 
#define 	GX_ENABLE   1 
#define 	GX_EQUAL   2 
#define 	GX_F32   4 
#define 	GX_FALSE   0 
#define 	GX_FIFO_HIWATERMARK   (16*1024) 
#define 	GX_FIFO_MINSIZE   (64*1024) 
#define 	GX_FIFO_OBJSIZE   128 
#define 	GX_FOG_EXP   GX_FOG_PERSP_EXP 
#define 	GX_FOG_EXP2   GX_FOG_PERSP_EXP2 
#define 	GX_FOG_LIN   GX_FOG_PERSP_LIN 
#define 	GX_FOG_NONE   0 
#define 	GX_FOG_ORTHO_EXP   12 
#define 	GX_FOG_ORTHO_EXP2   13 
#define 	GX_FOG_ORTHO_LIN   10 
#define 	GX_FOG_ORTHO_REVEXP   14 
#define 	GX_FOG_ORTHO_REVEXP2   15 
#define 	GX_FOG_PERSP_EXP   4 
#define 	GX_FOG_PERSP_EXP2   5 
#define 	GX_FOG_PERSP_LIN   2 
#define 	GX_FOG_PERSP_REVEXP   6 
#define 	GX_FOG_PERSP_REVEXP2   7 
#define 	GX_FOG_REVEXP   GX_FOG_PERSP_REVEXP 
#define 	GX_FOG_REVEXP2   GX_FOG_PERSP_REVEXP2 
#define 	GX_GEQUAL   6 
#define 	GX_GM_1_0   0 
#define 	GX_GM_1_7   1 
#define 	GX_GM_2_2   2 
#define 	GX_GREATER   4 
#define 	GX_IDENTITY   60 
#define 	GX_INDEX16   3 
#define 	GX_INDEX8   2 
#define 	GX_INDTEXSTAGE0   0 
#define 	GX_INDTEXSTAGE1   1 
#define 	GX_INDTEXSTAGE2   2 
#define 	GX_INDTEXSTAGE3   3 
#define 	GX_InitLightDirv(lo, vec)   (GX_InitLightDir((lo), *(f32*)(vec), *((f32*)(vec)+1), *((f32*)(vec)+2))) 	//Sets the direction of a light in the light object using a vector structure. More... 
#define 	GX_InitLightPosv(lo, vec)   (GX_InitLightPos((lo), *(f32*)(vec), *((f32*)(vec)+1), *((f32*)(vec)+2))) 	//Sets the position of the light in the light object using a vector structure. More... 
#define 	GX_InitLightShininess(lobj, shininess) 	//Sets shininess of a per-vertex specular light. More... 
#define 	GX_InitSpecularDirHAv(lo, vec0, vec1) 	//Sets the direction and half-angle vector of a specular light in the light object using a vector. More... 
#define 	GX_InitSpecularDirv(lo, vec)   (GX_InitSpecularDir((lo), *(f32*)(vec), *((f32*)(vec)+1), *((f32*)(vec)+2))) 	//Sets the direction of a specular light in the light object using a vector. More... 
#define 	GX_ITB_NONE   0 
#define 	GX_ITB_S   1 
#define 	GX_ITB_ST   3 
#define 	GX_ITB_STU   7 
#define 	GX_ITB_SU   5 
#define 	GX_ITB_T   2 
#define 	GX_ITB_TU   6 
#define 	GX_ITB_U   4 
#define 	GX_ITBA_OFF   0 
#define 	GX_ITBA_S   1 
#define 	GX_ITBA_T   2 
#define 	GX_ITBA_U   3 
#define 	GX_ITF_3   3 
#define 	GX_ITF_4   2 
#define 	GX_ITF_5   1 
#define 	GX_ITF_8   0 
#define 	GX_ITM_0   1 
#define 	GX_ITM_1   2 
#define 	GX_ITM_2   3 
#define 	GX_ITM_OFF   0 
#define 	GX_ITM_S0   5 
#define 	GX_ITM_S1   6 
#define 	GX_ITM_S2   7 
#define 	GX_ITM_T0   9 
#define 	GX_ITM_T1   10 
#define 	GX_ITM_T2   11 
#define 	GX_ITS_1   0 
#define 	GX_ITS_128   7 
#define 	GX_ITS_16   4 
#define 	GX_ITS_2   1 
#define 	GX_ITS_256   8 
#define 	GX_ITS_32   5 
#define 	GX_ITS_4   2 
#define 	GX_ITS_64   6 
#define 	GX_ITS_8   3 
#define 	GX_ITW_0   6 
#define 	GX_ITW_128   2 
#define 	GX_ITW_16   5 
#define 	GX_ITW_256   1 
#define 	GX_ITW_32   4 
#define 	GX_ITW_64   3 
#define 	GX_ITW_OFF   0 
#define 	GX_KCOLOR0   0 
#define 	GX_KCOLOR1   1 
#define 	GX_KCOLOR2   2 
#define 	GX_KCOLOR3   3 
#define 	GX_KCOLOR_MAX   4 
#define 	GX_LEQUAL   3 
#define 	GX_LESS   1 
#define 	GX_LIGHT0   0x001 
#define 	GX_LIGHT1   0x002 
#define 	GX_LIGHT2   0x004 
#define 	GX_LIGHT3   0x008 
#define 	GX_LIGHT4   0x010 
#define 	GX_LIGHT5   0x020 
#define 	GX_LIGHT6   0x040 
#define 	GX_LIGHT7   0x080 
#define 	GX_LIGHTARRAY   24 
#define 	GX_LIGHTNULL   0x000 
#define 	GX_LIN_MIP_LIN   5 
#define 	GX_LIN_MIP_NEAR   3 
#define 	GX_LINEAR   1 
#define 	GX_LINES   0xA8 
#define 	GX_LINESTRIP   0xB0 
#define 	GX_LO_AND   1 
#define 	GX_LO_CLEAR   0 
#define 	GX_LO_COPY   3 
#define 	GX_LO_EQUIV   9 
#define 	GX_LO_INV   10 
#define 	GX_LO_INVAND   4 
#define 	GX_LO_INVCOPY   12 
#define 	GX_LO_INVOR   13 
#define 	GX_LO_NAND   14 
#define 	GX_LO_NOOP   5 
#define 	GX_LO_NOR   8 
#define 	GX_LO_OR   7 
#define 	GX_LO_REVAND   2 
#define 	GX_LO_REVOR   11 
#define 	GX_LO_SET   15 
#define 	GX_LO_XOR   6 
#define 	GX_MAX_ALPHAOP   4 
#define 	GX_MAX_ANISOTROPY   3 
#define 	GX_MAX_BLENDMODE   4 
#define 	GX_MAX_INDTEXSTAGE   4 
#define 	GX_MAX_ITBALPHA   4 
#define 	GX_MAX_ITBIAS   8 
#define 	GX_MAX_ITFORMAT   4 
#define 	GX_MAX_ITSCALE   9 
#define 	GX_MAX_ITWRAP   7 
#define 	GX_MAX_TEVBIAS   3 
#define 	GX_MAX_TEVCLAMPMODE   4 
#define 	GX_MAX_TEVREG   4 
#define 	GX_MAX_TEVSCALE   4 
#define 	GX_MAX_TEVSTAGE   16 
#define 	GX_MAX_TEVSWAP   4 
#define 	GX_MAX_TEXMAP   8 
#define 	GX_MAX_TEXOFFSET   6 
#define 	GX_MAX_VTXATTRFMT   GX_VA_MAXATTR 
#define 	GX_MAX_VTXATTRFMT_LISTSIZE   (GX_VA_MAXATTR+1) 
#define 	GX_MAX_VTXDESC   GX_VA_MAXATTR 
#define 	GX_MAX_VTXDESC_LISTSIZE   (GX_VA_MAXATTR+1) 
#define 	GX_MAX_Z24   0x00ffffff 
#define 	GX_MAX_ZTEXOP   3 
#define 	GX_MAXCOORD   0x8 
#define 	GX_MAXLIGHT   0x100 
#define 	GX_MAXTEXWRAPMODE   3 
#define 	GX_MAXVTXFMT   8 
#define 	GX_MIRROR   2 
#define 	GX_MODULATE   0 
#define 	GX_MT_DL_SAVE_CTX   2 
#define 	GX_MT_NULL   0 
#define 	GX_MT_XF_FLUSH   1 
#define 	GX_MTX2x4   1 
#define 	GX_MTX3x4   0 
#define 	GX_NEAR   0 
#define 	GX_NEAR_MIP_LIN   4 
#define 	GX_NEAR_MIP_NEAR   2 
#define 	GX_NEQUAL   5 
#define 	GX_NEVER   0 
#define 	GX_NONE   0 
#define 	GX_NRM_NBT   1 
#define 	GX_NRM_NBT3   2 
#define 	GX_NRM_XYZ   0 
#define 	GX_NRMMTXARRAY   22 
#define 	GX_ORTHOGRAPHIC   1 
#define 	GX_PASSCLR   4 
#define 	GX_PERF0_AVG_QUAD_CNT   33 
#define 	GX_PERF0_CLIP_CLKS   2 
#define 	GX_PERF0_CLIP_RATIO   10 
#define 	GX_PERF0_CLIP_VTX   1 
#define 	GX_PERF0_CLOCKS   34 
#define 	GX_PERF0_NONE   35 
#define 	GX_PERF0_QUAD_0CVG   27 
#define 	GX_PERF0_QUAD_1CVG   29 
#define 	GX_PERF0_QUAD_2CVG   30 
#define 	GX_PERF0_QUAD_3CVG   31 
#define 	GX_PERF0_QUAD_4CVG   32 
#define 	GX_PERF0_QUAD_NON0CVG   28 
#define 	GX_PERF0_TRIANGLES   11 
#define 	GX_PERF0_TRIANGLES_0CLR   24 
#define 	GX_PERF0_TRIANGLES_0TEX   15 
#define 	GX_PERF0_TRIANGLES_1CLR   25 
#define 	GX_PERF0_TRIANGLES_1TEX   16 
#define 	GX_PERF0_TRIANGLES_2CLR   26 
#define 	GX_PERF0_TRIANGLES_2TEX   17 
#define 	GX_PERF0_TRIANGLES_3TEX   18 
#define 	GX_PERF0_TRIANGLES_4TEX   19 
#define 	GX_PERF0_TRIANGLES_5TEX   20 
#define 	GX_PERF0_TRIANGLES_6TEX   21 
#define 	GX_PERF0_TRIANGLES_7TEX   22 
#define 	GX_PERF0_TRIANGLES_8TEX   23 
#define 	GX_PERF0_TRIANGLES_CULLED   12 
#define 	GX_PERF0_TRIANGLES_PASSED   13 
#define 	GX_PERF0_TRIANGLES_SCISSORED   14 
#define 	GX_PERF0_VERTICES   0 
#define 	GX_PERF0_XF_BOT_CLKS   7 
#define 	GX_PERF0_XF_LIT_CLKS   6 
#define 	GX_PERF0_XF_REGLD_CLKS   8 
#define 	GX_PERF0_XF_REGRD_CLKS   9 
#define 	GX_PERF0_XF_WAIT_IN   3 
#define 	GX_PERF0_XF_WAIT_OUT   4 
#define 	GX_PERF0_XF_XFRM_CLKS   5 
#define 	GX_PERF1_CALL_REQ   18 
#define 	GX_PERF1_CLOCKS   21 
#define 	GX_PERF1_CP_ALL_REQ   20 
#define 	GX_PERF1_FIFO_REQ   17 
#define 	GX_PERF1_NONE   22 
#define 	GX_PERF1_TC_CHECK1_2   4 
#define 	GX_PERF1_TC_CHECK3_4   5 
#define 	GX_PERF1_TC_CHECK5_6   6 
#define 	GX_PERF1_TC_CHECK7_8   7 
#define 	GX_PERF1_TC_MISS   8 
#define 	GX_PERF1_TEXELS   0 
#define 	GX_PERF1_TX_IDLE   1 
#define 	GX_PERF1_TX_MEMSTALL   3 
#define 	GX_PERF1_TX_REGS   2 
#define 	GX_PERF1_VC_ALL_STALLS   15 
#define 	GX_PERF1_VC_ELEMQ_FULL   9 
#define 	GX_PERF1_VC_MEMREQ_FULL   11 
#define 	GX_PERF1_VC_MISS_REQ   19 
#define 	GX_PERF1_VC_MISSQ_FULL   10 
#define 	GX_PERF1_VC_MISSREP_FULL   13 
#define 	GX_PERF1_VC_STATUS7   12 
#define 	GX_PERF1_VC_STREAMBUF_LOW   14 
#define 	GX_PERF1_VERTICES   16 
#define 	GX_PERSPECTIVE   0 
#define 	GX_PF_RGB565_Z16   2 
#define 	GX_PF_RGB8_Z24   0 
#define 	GX_PF_RGBA6_Z24   1 
#define 	GX_PF_U8   5 
#define 	GX_PF_V8   6 
#define 	GX_PF_Y8   4 
#define 	GX_PF_YUV420   7 
#define 	GX_PF_Z24   3 
#define 	GX_PNMTX0   0 
#define 	GX_PNMTX1   3 
#define 	GX_PNMTX2   6 
#define 	GX_PNMTX3   9 
#define 	GX_PNMTX4   12 
#define 	GX_PNMTX5   15 
#define 	GX_PNMTX6   18 
#define 	GX_PNMTX7   21 
#define 	GX_PNMTX8   24 
#define 	GX_PNMTX9   27 
#define 	GX_POINTS   0xB8 
#define 	GX_POS_XY   0 
#define 	GX_POS_XYZ   1 
#define 	GX_POSMTXARRAY   21 
#define 	GX_QUADS   0x80 
#define 	GX_READ_00   0 
#define 	GX_READ_FF   1 
#define 	GX_READ_NONE   2 
#define 	GX_REPEAT   1 
#define 	GX_REPLACE   3 
#define 	GX_RGB565   0 
#define 	GX_RGB8   1 
#define 	GX_RGBA4   3 
#define 	GX_RGBA6   4 
#define 	GX_RGBA8   5 
#define 	GX_RGBX8   2 
#define 	GX_S16   3 
#define 	GX_S8   1 
#define 	GX_SP_COS   2 
#define 	GX_SP_COS2   3 
#define 	GX_SP_FLAT   1 
#define 	GX_SP_OFF   0 
#define 	GX_SP_RING1   5 
#define 	GX_SP_RING2   6 
#define 	GX_SP_SHARP   4 
#define 	GX_SRC_REG   0 
#define 	GX_SRC_VTX   1 
#define 	GX_TB_ADDHALF   1 
#define 	GX_TB_SUBHALF   2 
#define 	GX_TB_ZERO   0 
#define 	GX_TC_EQ   2 
#define 	GX_TC_GE   1 
#define 	GX_TC_LE   3 
#define 	GX_TC_LINEAR   0 
#define 	GX_TEV_ADD   0 
#define 	GX_TEV_COMP_A8_EQ   GX_TEV_COMP_RGB8_EQ 
#define 	GX_TEV_COMP_A8_GT   GX_TEV_COMP_RGB8_GT 
#define 	GX_TEV_COMP_BGR24_EQ   13 
#define 	GX_TEV_COMP_BGR24_GT   12 
#define 	GX_TEV_COMP_GR16_EQ   11 
#define 	GX_TEV_COMP_GR16_GT   10 
#define 	GX_TEV_COMP_R8_EQ   9 
#define 	GX_TEV_COMP_R8_GT   8 
#define 	GX_TEV_COMP_RGB8_EQ   15 
#define 	GX_TEV_COMP_RGB8_GT   14 
#define 	GX_TEV_KASEL_1   0x00 
#define 	GX_TEV_KASEL_1_2   0x04 
#define 	GX_TEV_KASEL_1_4   0x06 
#define 	GX_TEV_KASEL_1_8   0x07 
#define 	GX_TEV_KASEL_3_4   0x02 
#define 	GX_TEV_KASEL_3_8   0x05 
#define 	GX_TEV_KASEL_5_8   0x03 
#define 	GX_TEV_KASEL_7_8   0x01 
#define 	GX_TEV_KASEL_K0_A   0x1C 
#define 	GX_TEV_KASEL_K0_B   0x18 
#define 	GX_TEV_KASEL_K0_G   0x14 
#define 	GX_TEV_KASEL_K0_R   0x10 
#define 	GX_TEV_KASEL_K1_A   0x1D 
#define 	GX_TEV_KASEL_K1_B   0x19 
#define 	GX_TEV_KASEL_K1_G   0x15 
#define 	GX_TEV_KASEL_K1_R   0x11 
#define 	GX_TEV_KASEL_K2_A   0x1E 
#define 	GX_TEV_KASEL_K2_B   0x1A 
#define 	GX_TEV_KASEL_K2_G   0x16 
#define 	GX_TEV_KASEL_K2_R   0x12 
#define 	GX_TEV_KASEL_K3_A   0x1F 
#define 	GX_TEV_KASEL_K3_B   0x1B 
#define 	GX_TEV_KASEL_K3_G   0x17 
#define 	GX_TEV_KASEL_K3_R   0x13 
#define 	GX_TEV_KCSEL_1   0x00 
#define 	GX_TEV_KCSEL_1_2   0x04 
#define 	GX_TEV_KCSEL_1_4   0x06 
#define 	GX_TEV_KCSEL_1_8   0x07 
#define 	GX_TEV_KCSEL_3_4   0x02 
#define 	GX_TEV_KCSEL_3_8   0x05 
#define 	GX_TEV_KCSEL_5_8   0x03 
#define 	GX_TEV_KCSEL_7_8   0x01 
#define 	GX_TEV_KCSEL_K0   0x0C 
#define 	GX_TEV_KCSEL_K0_A   0x1C 
#define 	GX_TEV_KCSEL_K0_B   0x18 
#define 	GX_TEV_KCSEL_K0_G   0x14 
#define 	GX_TEV_KCSEL_K0_R   0x10 
#define 	GX_TEV_KCSEL_K1   0x0D 
#define 	GX_TEV_KCSEL_K1_A   0x1D 
#define 	GX_TEV_KCSEL_K1_B   0x19 
#define 	GX_TEV_KCSEL_K1_G   0x15 
#define 	GX_TEV_KCSEL_K1_R   0x11 
#define 	GX_TEV_KCSEL_K2   0x0E 
#define 	GX_TEV_KCSEL_K2_A   0x1E 
#define 	GX_TEV_KCSEL_K2_B   0x1A 
#define 	GX_TEV_KCSEL_K2_G   0x16 
#define 	GX_TEV_KCSEL_K2_R   0x12 
#define 	GX_TEV_KCSEL_K3   0x0F 
#define 	GX_TEV_KCSEL_K3_A   0x1F 
#define 	GX_TEV_KCSEL_K3_B   0x1B 
#define 	GX_TEV_KCSEL_K3_G   0x17 
#define 	GX_TEV_KCSEL_K3_R   0x13 
#define 	GX_TEV_SUB   1 
#define 	GX_TEV_SWAP0   0 
#define 	GX_TEV_SWAP1   1 
#define 	GX_TEV_SWAP2   2 
#define 	GX_TEV_SWAP3   3 
#define 	GX_TEVPREV   0 
#define 	GX_TEVREG0   1 
#define 	GX_TEVREG1   2 
#define 	GX_TEVREG2   3 
#define 	GX_TEVSTAGE0   0 
#define 	GX_TEVSTAGE1   1 
#define 	GX_TEVSTAGE10   10 
#define 	GX_TEVSTAGE11   11 
#define 	GX_TEVSTAGE12   12 
#define 	GX_TEVSTAGE13   13 
#define 	GX_TEVSTAGE14   14 
#define 	GX_TEVSTAGE15   15 
#define 	GX_TEVSTAGE2   2 
#define 	GX_TEVSTAGE3   3 
#define 	GX_TEVSTAGE4   4 
#define 	GX_TEVSTAGE5   5 
#define 	GX_TEVSTAGE6   6 
#define 	GX_TEVSTAGE7   7 
#define 	GX_TEVSTAGE8   8 
#define 	GX_TEVSTAGE9   9 
#define 	GX_TEX_S   0 
#define 	GX_TEX_ST   1 
#define 	GX_TEXCACHE_128K   1 
#define 	GX_TEXCACHE_32K   0 
#define 	GX_TEXCACHE_512K   2 
#define 	GX_TEXCACHE_NONE   3 
#define 	GX_TEXCOORD0   0x0 
#define 	GX_TEXCOORD1   0x1 
#define 	GX_TEXCOORD2   0x2 
#define 	GX_TEXCOORD3   0x3 
#define 	GX_TEXCOORD4   0x4 
#define 	GX_TEXCOORD5   0x5 
#define 	GX_TEXCOORD6   0x6 
#define 	GX_TEXCOORD7   0x7 
#define 	GX_TEXCOORDNULL   0xff 
#define 	GX_TEXMAP0   0 
#define 	GX_TEXMAP1   1 
#define 	GX_TEXMAP2   2 
#define 	GX_TEXMAP3   3 
#define 	GX_TEXMAP4   4 
#define 	GX_TEXMAP5   5 
#define 	GX_TEXMAP6   6 
#define 	GX_TEXMAP7   7 
#define 	GX_TEXMAP_DISABLE   0x100 
#define 	GX_TEXMAP_NULL   0xff 
#define 	GX_TEXMTX0   30 
#define 	GX_TEXMTX1   33 
#define 	GX_TEXMTX2   36 
#define 	GX_TEXMTX3   39 
#define 	GX_TEXMTX4   42 
#define 	GX_TEXMTX5   45 
#define 	GX_TEXMTX6   48 
#define 	GX_TEXMTX7   51 
#define 	GX_TEXMTX8   54 
#define 	GX_TEXMTX9   57 
#define 	GX_TEXMTXARRAY   23 
#define 	GX_TF_A8   GX_CTF_A8 
#define 	GX_TF_CI14   0xa 
#define 	GX_TF_CI4   0x8 
#define 	GX_TF_CI8   0x9 
#define 	GX_TF_CMPR   0xE 
#define 	GX_TF_I4   0x0 
#define 	GX_TF_I8   0x1 
#define 	GX_TF_IA4   0x2 
#define 	GX_TF_IA8   0x3 
#define 	GX_TF_RGB565   0x4 
#define 	GX_TF_RGB5A3   0x5 
#define 	GX_TF_RGBA8   0x6 
#define 	GX_TF_Z16   (0x3|_GX_TF_ZTF) 
#define 	GX_TF_Z24X8   (0x6|_GX_TF_ZTF) 
#define 	GX_TF_Z8   (0x1|_GX_TF_ZTF) 
#define 	GX_TG_BINRM   2 
#define 	GX_TG_BUMP0   2 
#define 	GX_TG_BUMP1   3 
#define 	GX_TG_BUMP2   4 
#define 	GX_TG_BUMP3   5 
#define 	GX_TG_BUMP4   6 
#define 	GX_TG_BUMP5   7 
#define 	GX_TG_BUMP6   8 
#define 	GX_TG_BUMP7   9 
#define 	GX_TG_COLOR0   19 
#define 	GX_TG_COLOR1   20 
#define 	GX_TG_MTX2x4   1 
#define 	GX_TG_MTX3x4   0 
#define 	GX_TG_NRM   1 
#define 	GX_TG_POS   0 
#define 	GX_TG_SRTG   10 
#define 	GX_TG_TANGENT   3 
#define 	GX_TG_TEX0   4 
#define 	GX_TG_TEX1   5 
#define 	GX_TG_TEX2   6 
#define 	GX_TG_TEX3   7 
#define 	GX_TG_TEX4   8 
#define 	GX_TG_TEX5   9 
#define 	GX_TG_TEX6   10 
#define 	GX_TG_TEX7   11 
#define 	GX_TG_TEXCOORD0   12 
#define 	GX_TG_TEXCOORD1   13 
#define 	GX_TG_TEXCOORD2   14 
#define 	GX_TG_TEXCOORD3   15 
#define 	GX_TG_TEXCOORD4   16 
#define 	GX_TG_TEXCOORD5   17 
#define 	GX_TG_TEXCOORD6   18 
#define 	GX_TL_IA8   0x00 
#define 	GX_TL_RGB565   0x01 
#define 	GX_TL_RGB5A3   0x02 
#define 	GX_TLUT0   0 
#define 	GX_TLUT1   1 
#define 	GX_TLUT10   10 
#define 	GX_TLUT11   11 
#define 	GX_TLUT12   12 
#define 	GX_TLUT13   13 
#define 	GX_TLUT14   14 
#define 	GX_TLUT15   15 
#define 	GX_TLUT2   2 
#define 	GX_TLUT3   3 
#define 	GX_TLUT4   4 
#define 	GX_TLUT5   5 
#define 	GX_TLUT6   6 
#define 	GX_TLUT7   7 
#define 	GX_TLUT8   8 
#define 	GX_TLUT9   9 
#define 	GX_TLUT_128   8 
#define 	GX_TLUT_16   1 
#define 	GX_TLUT_16K   1024 
#define 	GX_TLUT_1K   64 
#define 	GX_TLUT_256   16 
#define 	GX_TLUT_2K   128 
#define 	GX_TLUT_32   2 
#define 	GX_TLUT_4K   256 
#define 	GX_TLUT_512   32 
#define 	GX_TLUT_64   4 
#define 	GX_TLUT_8K   512 
#define 	GX_TO_EIGHTH   2 
#define 	GX_TO_FOURTH   3 
#define 	GX_TO_HALF   4 
#define 	GX_TO_ONE   5 
#define 	GX_TO_SIXTEENTH   1 
#define 	GX_TO_ZERO   0 
#define 	GX_TRIANGLEFAN   0xA0 
#define 	GX_TRIANGLES   0x90 
#define 	GX_TRIANGLESTRIP   0x98 
#define 	GX_TRUE   1 
#define 	GX_U16   2 
#define 	GX_U8   0 
#define 	GX_VA_CLR0   11 
#define 	GX_VA_CLR1   12 
#define 	GX_VA_MAXATTR   26 
#define 	GX_VA_NBT   25 
#define 	GX_VA_NRM   10 
#define 	GX_VA_NULL   0xff 
#define 	GX_VA_POS   9 
#define 	GX_VA_PTNMTXIDX   0 
#define 	GX_VA_TEX0   13 
#define 	GX_VA_TEX0MTXIDX   1 
#define 	GX_VA_TEX1   14 
#define 	GX_VA_TEX1MTXIDX   2 
#define 	GX_VA_TEX2   15 
#define 	GX_VA_TEX2MTXIDX   3 
#define 	GX_VA_TEX3   16 
#define 	GX_VA_TEX3MTXIDX   4 
#define 	GX_VA_TEX4   17 
#define 	GX_VA_TEX4MTXIDX   5 
#define 	GX_VA_TEX5   18 
#define 	GX_VA_TEX5MTXIDX   6 
#define 	GX_VA_TEX6   19 
#define 	GX_VA_TEX6MTXIDX   7 
#define 	GX_VA_TEX7   20 
#define 	GX_VA_TEX7MTXIDX   8 
#define 	GX_VC_ALL   15 
#define 	GX_VC_CLR0   2 
#define 	GX_VC_CLR1   3 
#define 	GX_VC_NRM   1 
#define 	GX_VC_POS   0 
#define 	GX_VC_TEX0   4 
#define 	GX_VC_TEX1   5 
#define 	GX_VC_TEX2   6 
#define 	GX_VC_TEX3   7 
#define 	GX_VC_TEX4   8 
#define 	GX_VC_TEX5   9 
#define 	GX_VC_TEX6   10 
#define 	GX_VC_TEX7   11 
#define 	GX_VTXFMT0   0 
#define 	GX_VTXFMT1   1 
#define 	GX_VTXFMT2   2 
#define 	GX_VTXFMT3   3 
#define 	GX_VTXFMT4   4 
#define 	GX_VTXFMT5   5 
#define 	GX_VTXFMT6   6 
#define 	GX_VTXFMT7   7 
#define 	GX_XF_FLUSH_NONE   0 
#define 	GX_XF_FLUSH_SAFE   1 
#define 	GX_ZC_FAR   3 
#define 	GX_ZC_LINEAR   0 
#define 	GX_ZC_MID   2 
#define 	GX_ZC_NEAR   1 
#define 	GX_ZT_ADD   1 
#define 	GX_ZT_DISABLE   0 
#define 	GX_ZT_REPLACE   2